### ISSUE TITLE
Count block usage by category

### ISSUE THREAD

**Issue by fenwickjb** [JaysGitLab/cs-5666-scatt-jacc-caj#26]
A Scratch program is a collection of interacting sprites. Each sprite has a collection of interacting scripts. Each script is a sequence of blocks. Some blocks allow nesting of other blocks (e.g., loops).

Scratch "categorizes" the 150'ish available blocks by their function. For example, the "Motion" blocks are in the _Motion_ block "palette" and have a dark blue color. 

We want to be able to count how many of the _Motion_ blocks are used. Probably want to know this information for all of the various block categories per script, per sprite, per entire program.

**Comment by thehunte199** [comment]
Going to give this a shot.
