### ISSUE TITLE
User Experience

### ISSUE THREAD

**Issue by whereswaldon** [JaysGitLab/cs-5666-scatt-jacc-caj#33]
I don't think that our tool is very easy to understand right now. I say this because I was just trying to use it, and it took a while to figure out how. I'd like to talk through a few UI concerns:

1) Why do we only see directories in the file picker?
2) How do you know when it worked or didn't work?
3) How do you know where it put the report that it generates?

I can answer these questions by reading the source code, but the poor middle-school teachers who comprise our target audience won't want to do that. I'm not really sure the best way to address some of these, but here are some ideas:

- Print the names of sb2 files into the console log when they are found in the selected directory.
- Print the location of the report to the console log.
- Print the report to a file *and* to console log?

@bclinthall @ejcole @thehunte199 What do you guys think?

**Comment by bclinthall** [comment]
Good issue, Chris.  This maybe just highlights the problem, but what console log?

**Comment by whereswaldon** [comment]
`System.out.println`? I've been running our app from the command line. If you're double-clicking on the `scatt.bat` script or something... <shudder> How do you run the app?

**Comment by bclinthall** [comment]
I've been running from command line too, but if we're concerned about middle school teachers, we need a way to run that doesn't involve opening a scary terminal where accidentally `typing sudo rm -rf /` will kill everything.

**Comment by whereswaldon** [comment]
You're right. This was something of a stop-gap measure. I guess we need a pop-up that tells the user what happened.

**Comment by whereswaldon** [comment]
I think that #41 Adequately addresses this, so this is resolved
