### ISSUE TITLE
File Chooser

### ISSUE THREAD

**Issue by bclinthall** [JaysGitLab/cs-5666-scatt-jacc-caj#4]
Implement a file chooser.  Here's how: http://docs.oracle.com/javase/tutorial/uiswing/components/filechooser.html.
Have it print the path of the file chosen to console.

**Comment by thehunte199** [comment]
Working on the test for this currently. Hoping to finish within the hour.

**Comment by thehunte199** [comment]
Assigning a 3 hr label estimation. Going to work for 1 tonight to develop the test.

**Comment by ejcole** [comment]
We have merged this to master and this is resolved now.
